### ISSUE TITLE
Node Version Support and n-api

### ISSUE THREAD

**Issue by ccollie** [mcollina/native-hdr-histogram#34]
Do we have a minimum node version requirement ? If it's 8+ would it be wise to switch to `n-api` ?

**Comment by mcollina** [comment]
last time I checked, it slowed things down quite a bit. If things have improved, happy to merge!
Il 18 nov 2019, 23:38 +0100, Clayton Collie <notifications@github.com>, ha scritto:

**Comment by vweevers** [comment]
Yes, the minimum node version is 8. Even if it wasn't, an N-API rewrite is worth a major release anyway.

@mcollina In `leveldown` and `rocksdb` we actually saw a slight speedup.

**Comment by mcollina** [comment]
it 's worth a test, I checked when n-api was still experimental.

**Comment by ccollie** [comment]
I'd be willing to devote some time to this. If this merits a major release in any case, I've added more API coverage I'd like to get in :

https://github.com/ccollie/native-hdr-histogram/commit/6e56755f92261deaa9bd1f5e18853f8d2e8230e1

**Comment by mcollina** [comment]
Definitely!
Il 19 nov 2019, 21:41 +0100, Clayton Collie <notifications@github.com>, ha scritto:

**Comment by ccollie** [comment]
Ok. I'll start working on it.

**Comment by jschlight** [comment]
Based on a discussion @mcollina and I had at Node+JS Interactive 2019 in Montreal, I've used our automated tool to create an N-API binding that is meant to be API-compatible with `native-hdr-histogram`. The initial release, which passes all of the unit tests for this module, is available for review in a separate repository:

https://github.com/inspiredware/node-hdr-histogram-napi

There is one issue with the `Histogram` constructor that I still need to verify. Apparently it is expected to work differently whether it's called with `new` or not. I still need to verify that operation, but wanted to get this initial implementation up right away for review and comment. 

Because the generator tool is automated, we've been able to add additional methods that were not previously implemented. Pulling everything together to generate this particular binding took some additional time because we needed to add the ability to our tool to generate pseudo classes from the C functions. I'm open to any suggestions for additional methods or classes you would like to see implemented. 

The binding is currently generated as a separate project because that's how our tool is designed to work. If it is of benefit to the community I am not averse to creating a PR to merge the N-API code into this repository. If it’s better to keep it a separate project, I’m happy to do that, too. 

But I wanted to get feedback from this project on the work we’ve completed so far before charging in here like a bull.

**Comment by mcollina** [comment]
> There is one issue with the Histogram constructor that I still need to verify. Apparently it is expected to work differently whether it's called with new or not. I still need to verify that operation, but wanted to get this initial implementation up right away for review and comment.

I'm happy to release a major that drops this feature.

**Comment by mcollina** [comment]
I've added you to this repo, feel free to send a PR.

**Comment by jschlight** [comment]
I've updated the [repo](https://github.com/inspiredware/node-hdr-histogram-napi) where I'm generating the N-API binding to include the functions and unit tests added by @ccollie in this PR: https://github.com/mcollina/native-hdr-histogram/pull/35. The repo also includes new functions I've added in addition to those added by @ccollie. 

My plan now is to:

- Implement unit tests to verify the additional functions I've added 
- Create documentation for the additional functions I've added
- Create a PR here to merge in the generated binding

I am currently building with `prebuild`. I'd like to see about using GitHub Actions for CI/CD but it will take me a bit of time to ramp up with GitHub Actions.

**Comment by mcollina** [comment]
amazing work!

**Comment by jschlight** [comment]
I've made another update to the [repo](https://github.com/inspiredware/node-hdr-histogram-napi) where I'm generating the N-API binding. I'm having problems creating unit tests for the additional methods I've added which are shown in this table:

| Class                | Method                      | HdrHistogram_c                     |
| -------------------- | --------------------------- | ---------------------------------- |
| HdrHistogram         | recordAtomic ‡              | hdr_record_value_atomic            |
| HdrHistogram         | recordCorrectedValueAtomic  | hdr_record_corrected_value_atomic  |
| HdrHistogram         | recordCorrectedValues       | hdr_record_corrected_values        |
| HdrHistogram         | recordCorrectedValuesAtomic | hdr_record_corrected_values_atomic |
| HdrHistogram         | recordValuesAtomic          | hdr_record_values_atomic           |
| HdrHistogramIterator | initLinear                  | hdr_iter_linear_init               |
| HdrHistogramIterator | initLog                     | hdr_iter_log_init                  |
| HdrHistogramIterator | initRecorded                | hdr_iter_recorded_init             |

‡ This method will be renamed `recordValueAtomic` on the next iteration to keep the method names consistent.

------

I'm having difficulties understanding the purpose of the "atomic" and "corrected" operations implemented in `HdrHistogram_c` which makes it impossible for me to create meaningful unit tests. And I'm not sure the methods I've added are even of value to the users of this library. I'm confident that the binding code is correct, but I'm reluctant to make the code available without unit tests.

So some questions:

- Are the methods I've added of value to this project?
- If so, can I get some help creating the unit tests for the methods shown above?
- And while we're at it, are there other HdrHistogram_c functions the community would like to see available in the JavaScript API?

**Comment by ccollie** [comment]
AFAIR, the *atomic* methods are for use in threaded/concurrent environments where locking is necessary to prevent data corruption. Given the single-threaded nature of node, they aren't really useful.

The _corrected_ variants *are* useful because of the "Coordinated Omission" problem (google it)

As far as unit tests go, I simply looked at other implementations and modified their tests where appropriate.

One addition I'd like to see is _subtract_. I'm using HdrHistogram to record latencies over a sliding window, and I need to remove values when a slice of the window goes out of scope.

**Comment by mcollina** [comment]
I would focus on feature parity first then adding new methods anyway! Shipping an updated version of this would be amazing.

**Comment by jschlight** [comment]
The code and unit tests are now complete. Since the most recent update, the following methods have been removed as they are designed for multi-threaded support which is beyond the scope of this current effort:

```
recordCorrectedValueAtomic
recordCorrectedValuesAtomic
recordAtomic
recordValuesAtomic
```

The implementation of a `subtract` method will need to happen after this work is complete.  

The work in progress can be viewed at https://github.com/inspiredware/node-hdr-histogram-napi

I've forked this repo and will be submitting a PR as soon as I've updated the documentation.
